  
language: php

php:
  - 8.0
  - 7.4

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE devhub;'

script:
  - phpunit

services:
  - mysql

notifications:
  email: false
