version: "3.7"

networks:
  devhub:

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - public:/var/www/public:ro
      - storage:/var/www/storage/app/public:ro
      - nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
    networks:
      - devhub

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    volumes:
      - ./../data:/var/lib/mysql/
    ports:
      - '${FORWARD_DB_PORT:-4306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE:-devhub}'
      MYSQL_USER: '${DB_USERNAME:-root}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - devhub

  php:
    container_name: php
    image: ${REGISTRY:-localhost}/devhub:${IMAGE_TAG}
    restart: always
    volumes:
    - public:/var/www/public
    - storage:/var/www/storage/app/public
    - nginx:/var/www/.docker/production/nginx/
    ports:
      - "9000:9000"
    networks:
      - devhub

volumes:
  public:
  storage:
  nginx:
