version: "3.7"

networks:
  devhub:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8090:80"
    volumes_from:
      - php
    volumes:
      - ./.docker/develop/logs/nginx:/var/log/nginx/
      - ./.docker/develop/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/develop/nginx/sites-available:/etc/nginx/sites-available
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - devhub

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_DB_PORT:-4306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE:-devhub}'
      MYSQL_USER: '${DB_USERNAME:-root}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql/
      - ./.docker/develop/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - devhub

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - devhub


  php:
    image: ${REGISTRY:-localhost}/devhub:latest
    build:
      context: ./
      dockerfile: .docker/develop/php/Dockerfile
      cache_from:
        - ${REGISTRY:-localhost}/devhub:latest
    container_name: php
    volumes:
      - ./:/var/www/:cached
      - ./.docker/develop/php/xlaravel.pool.conf:/usr/local/etc/php-fpm.d/xlaravel.pool.conf
    ports:
      - "9000:9000"
    networks:
      - devhub

volumes:
  mysql:
    driver: local
