version: '3'

networks:
  devhub:

services:
  nginx:
    image: ${REGISTRY:-localhost}/devhub_nginx:cache
    build:
      context: ./
      dockerfile: .docker/develop/nginx/Dockerfile
      cache_from:
        - ${REGISTRY:-localhost}/devhub_nginx:cache
    container_name: nginx
    ports:
      - "8090:80"
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage
      - ./.docker/develop/logs/nginx:/var/log/nginx/
    depends_on:
      - php
      - mysql
      - mailhog
    networks:
      - devhub

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_DB_PORT:-4306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE:-devhub}'
      MYSQL_USER: '${DB_USERNAME:-root}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './.docker/develop/mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
    networks:
      - devhub

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - devhub

  php:
    image: ${REGISTRY:-localhost}/devhub:cache
    build:
      context: ./
      dockerfile: .docker/develop/php/Dockerfile
      cache_from:
        - ${REGISTRY:-localhost}/devhub:cache
    container_name: php
    volumes:
      - './:/var/www'
    ports:
      - "9000:9000"
    networks:
      - devhub
