version: "3.7"

networks:
  devhub:

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes_from:
      - php
    volumes:
      - nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - devhub

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    volumes:
      - ./../data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE:-devhub}'
      MYSQL_USER: '${DB_USERNAME:-root}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - devhub

  redis:
    container_name: redis
    image: redis:6.2-alpine
    networks:
      - devhub

  php:
    container_name: php
    image: ${REGISTRY:-localhost}/devhub:${IMAGE_TAG}
    restart: always
    volumes:
      - data:/var/www/
      - nginx:/var/www/.docker/production/nginx/
    networks:
      - devhub

volumes:
  nginx:
  data:
